# Generated by Django 4.0.3 on 2022-03-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(blank=True, max_length=100, verbose_name='Dominio')),
                ('logo', models.ImageField(blank=True, upload_to='configuracion', verbose_name='Logo')),
                ('logo_mini', models.ImageField(blank=True, upload_to='configuracion', verbose_name='Logo Mini')),
            ],
        ),
    ]
