# Generated by Django 4.0.3 on 2022-03-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['dominio'], 'verbose_name': 'App', 'verbose_name_plural': 'App'},
        ),
        migrations.AddField(
            model_name='app',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre'),
        ),
    ]
