# Generated by Django 4.0.3 on 2022-03-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_alter_app_options_app_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='fondo',
            field=models.ImageField(blank=True, upload_to='configuracion', verbose_name='Fondo'),
        ),
    ]
