# Generated by Django 4.0.3 on 2022-03-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_producto_codigo'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden_compra_detalle',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden_compra_detalle',
            name='cantidad',
            field=models.PositiveBigIntegerField(default=0, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='orden_compra_detalle',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='costo'),
        ),
    ]
