# Generated by Django 4.0.3 on 2022-03-24 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_orden_compra_detalle_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_compra_detalle',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.orden_compra'),
        ),
    ]
