# Generated by Django 4.0.3 on 2022-05-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_orden_venta_detalle_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=100, verbose_name='Clave')),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estados',
                'verbose_name_plural': 'Estados',
                'ordering': ['clave'],
            },
        ),
    ]
