# Generated by Django 4.0.3 on 2022-05-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_email_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
                ('is_cotizacion', models.BooleanField(default=False)),
                ('is_venta', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Correos',
                'verbose_name_plural': 'Correos',
                'ordering': ['correo'],
            },
        ),
    ]
