# Generated by Django 3.2.13 on 2022-05-22 04:08

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Caracteristica')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Caracteristicas',
                'verbose_name_plural': 'Caracteristicas',
                'ordering': ['caracteristica'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Categoria')),
                ('descripcion', models.CharField(help_text='Descripción de la Categoría', max_length=100)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='inventario.categoria')),
            ],
            options={
                'verbose_name': 'Categorias',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Marca')),
                ('descripcion', models.CharField(help_text='Descripción de la Marca', max_length=100)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marca',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Unidad_Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=100, unique=True, verbose_name='Unidad')),
                ('descripcion', models.CharField(help_text='Descripción de la Unidad Medida', max_length=100)),
            ],
            options={
                'verbose_name': 'Unidad Medida',
                'verbose_name_plural': 'Unidad Medida',
                'ordering': ['unidad'],
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo')),
                ('contenido', models.TextField(blank=True, max_length=400, verbose_name='Contenido')),
                ('estatus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estatus')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripcion')),
                ('imagen', models.ImageField(blank=True, upload_to='servicios', verbose_name='imagen')),
                ('slug', models.SlugField(editable=False, max_length=300)),
                ('caracteristicas', models.ManyToManyField(blank=True, to='inventario.Caracteristicas')),
            ],
            options={
                'verbose_name': 'Servicios',
                'verbose_name_plural': 'Servicios',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('codigo', models.CharField(blank=True, max_length=200, verbose_name='Codigo')),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripcion')),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Contenido')),
                ('estatus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estatus')),
                ('imagen', models.ImageField(blank=True, upload_to='productos', verbose_name='Imagen')),
                ('imagen2', models.ImageField(blank=True, upload_to='productos', verbose_name='Imagen2')),
                ('imagen3', models.ImageField(blank=True, upload_to='productos', verbose_name='Imagen3')),
                ('slug', models.SlugField(editable=False, max_length=300)),
                ('caracteristicas', models.ManyToManyField(blank=True, to='inventario.Caracteristicas')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.unidad_medida')),
            ],
            options={
                'verbose_name': 'Productos',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estructura_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField(default=0)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='inventario.estructura_producto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Estructura Productos',
                'verbose_name_plural': 'Estructura Productos',
                'ordering': ['producto'],
            },
        ),
        migrations.CreateModel(
            name='Especificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrupador', models.CharField(blank=True, max_length=100, verbose_name='Agrupador')),
                ('hp', models.IntegerField(default=0)),
                ('fases_x_volts', models.CharField(blank=True, max_length=100, verbose_name='Fases x Volts')),
                ('amp_contactor', models.IntegerField(default=0)),
                ('amp_nom', models.IntegerField(default=0)),
                ('rango_amp_relevador', models.CharField(blank=True, max_length=100, verbose_name='Rango Amp Relevador')),
                ('tension_plena', models.CharField(blank=True, max_length=100, verbose_name='Tension Plena')),
                ('estado_solido', models.CharField(blank=True, max_length=100, verbose_name='Estado Solido')),
                ('baterias', models.IntegerField(default=0)),
                ('hidroneumatico', models.CharField(blank=True, max_length=100, verbose_name='Hidroneumatico')),
                ('carcamo', models.CharField(blank=True, max_length=100, verbose_name='Carcamo')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('variador_1', models.CharField(blank=True, max_length=100, verbose_name='Variador 1')),
                ('variador_2', models.CharField(blank=True, max_length=100, verbose_name='Variador 2')),
                ('variador_3', models.CharField(blank=True, max_length=100, verbose_name='Variador 3')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Especificaciones',
                'verbose_name_plural': 'Especificaciones',
                'ordering': ['producto'],
            },
        ),
    ]
