# Generated by Django 4.0.3 on 2022-03-16 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_categoria_marca_unidad_medida_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estructura_producto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='inventario.producto'),
        ),
    ]
