# Generated by Django 4.0.3 on 2022-03-20 00:30

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_subcategoria_producto_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['codigo'], 'verbose_name': 'Productos', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.unidad_medida'),
        ),
    ]
