# Generated by Django 4.0.3 on 2022-04-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_producto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estatus',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='estatus'),
        ),
    ]
