# Generated by Django 4.0.3 on 2022-04-30 16:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_producto_estatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Caracteristica')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Caracteristicas',
                'verbose_name_plural': 'Caracteristicas',
                'ordering': ['caracteristica'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='productos', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='contenido',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estatus',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='contenido',
            field=models.TextField(blank=True, max_length=400, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='servicios', verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='producto',
            name='caracteristicas',
            field=models.ManyToManyField(blank=True, to='inventario.caracteristicas'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='caracteristicas',
            field=models.ManyToManyField(blank=True, to='inventario.caracteristicas'),
        ),
    ]
