# Generated by Django 4.0.3 on 2022-04-30 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_caracteristicas_producto_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=0)),
                ('fases_x_volts', models.CharField(blank=True, max_length=100, verbose_name='Fases x Volts')),
                ('amp_contactor', models.IntegerField(default=0)),
                ('amp_nom', models.IntegerField(default=0)),
                ('rango_amp_relevador', models.CharField(blank=True, max_length=100, verbose_name='Rango Amp Relevador')),
                ('tension_plena', models.CharField(blank=True, max_length=100, verbose_name='Tension Plena')),
                ('estado_solido', models.CharField(blank=True, max_length=100, verbose_name='Estado Solido')),
                ('baterias', models.IntegerField(default=0)),
                ('hidroneumatico', models.CharField(blank=True, max_length=100, verbose_name='Hidroneumatico')),
                ('carcamo', models.CharField(blank=True, max_length=100, verbose_name='Carcamo')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('variador_1', models.CharField(blank=True, max_length=100, verbose_name='Variador 1')),
                ('variador_2', models.CharField(blank=True, max_length=100, verbose_name='Variador 2')),
                ('variador_3', models.CharField(blank=True, max_length=100, verbose_name='Variador 3')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Especificaciones',
                'verbose_name_plural': 'Especificaciones',
                'ordering': ['producto'],
            },
        ),
    ]
