# Generated by Django 4.0.3 on 2022-05-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_especificaciones_agrupador'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='estatus',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estatus'),
        ),
    ]
