# Generated by Django 4.0.3 on 2022-05-04 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_servicios_estatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Productos', 'verbose_name_plural': 'Productos'},
        ),
    ]
