# Generated by Django 4.0.3 on 2022-05-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_producto_created_producto_modified_servicios_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen2',
            field=models.ImageField(blank=True, upload_to='productos', verbose_name='Imagen2'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen3',
            field=models.ImageField(blank=True, upload_to='productos', verbose_name='Imagen3'),
        ),
    ]
